// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANOVNsEWokjKNhJim-op5k7MNJpa7fH5Q',
    appId: '1:353752231090:web:c1fa59cb10dad521b7adab',
    messagingSenderId: '353752231090',
    projectId: 'mjeshtri-b3cdb',
    authDomain: 'mjeshtri-b3cdb.firebaseapp.com',
    storageBucket: 'mjeshtri-b3cdb.firebasestorage.app',
    measurementId: 'G-MWW56D8BYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnSYuuN6SD6kgiGn82wv7pOb7h358RSoY',
    appId: '1:353752231090:android:2ee1ab181e83f700b7adab',
    messagingSenderId: '353752231090',
    projectId: 'mjeshtri-b3cdb',
    storageBucket: 'mjeshtri-b3cdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1cLYQd0MPrnmTRZBqs5_Ygxv1hzrSjk',
    appId: '1:353752231090:ios:732b302821b5135db7adab',
    messagingSenderId: '353752231090',
    projectId: 'mjeshtri-b3cdb',
    storageBucket: 'mjeshtri-b3cdb.firebasestorage.app',
    iosBundleId: 'com.example.mjeshtri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1cLYQd0MPrnmTRZBqs5_Ygxv1hzrSjk',
    appId: '1:353752231090:ios:732b302821b5135db7adab',
    messagingSenderId: '353752231090',
    projectId: 'mjeshtri-b3cdb',
    storageBucket: 'mjeshtri-b3cdb.firebasestorage.app',
    iosBundleId: 'com.example.mjeshtri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANOVNsEWokjKNhJim-op5k7MNJpa7fH5Q',
    appId: '1:353752231090:web:53dec5114666c6c0b7adab',
    messagingSenderId: '353752231090',
    projectId: 'mjeshtri-b3cdb',
    authDomain: 'mjeshtri-b3cdb.firebaseapp.com',
    storageBucket: 'mjeshtri-b3cdb.firebasestorage.app',
    measurementId: 'G-PMGJMQW8PD',
  );
}
